import difflib


def quote_toml_string(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def render_bundle_toml(model: dict) -> str:
    lines: list[str] = []
    lines.append("# Auto-generated by `python tools/run.py config-migrate`.")
    lines.append("# Source of truth remains `config/program`; rerun migration after source updates.")
    lines.append("")
    lines.append(f"schema_version = {model['schema_version']}")
    lines.append(f"profile = {quote_toml_string(model['profile'])}")
    lines.append(f"bundle_name = {quote_toml_string(model['bundle_name'])}")
    lines.append("")

    required = model["file_list"]["required"]
    optional = model["file_list"]["optional"]
    lines.append("[file_list]")
    lines.append("required = [")
    for item in required:
        lines.append(f"  {quote_toml_string(item)},")
    lines.append("]")
    lines.append("optional = [")
    for item in optional:
        lines.append(f"  {quote_toml_string(item)},")
    lines.append("]")
    lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def print_diff(from_text: str, to_text: str, from_name: str, to_name: str) -> None:
    diff = difflib.unified_diff(
        from_text.splitlines(),
        to_text.splitlines(),
        fromfile=from_name,
        tofile=to_name,
        lineterm="",
    )
    for line in diff:
        print(line)
