if(TT_CPP20_MODULES_EFFECTIVE)
    set(TIME_TRACKER_INFRA_REPORTS_EXPORT_SOURCES
        "reports/export_utils.module.cpp"
        "reports/exporter.module.cpp"
        "reports/report_file_manager.module.cpp"
    )
else()
    set(TIME_TRACKER_INFRA_REPORTS_EXPORT_SOURCES
        "reports/export_utils.cpp"
        "reports/exporter.cpp"
        "reports/report_file_manager.cpp"
    )
endif()

if(TT_CPP20_MODULES_EFFECTIVE)
    set(TIME_TRACKER_INFRA_REPORTS_DTO_SOURCES
        "reports/report_dto_export_writer.module.cpp"
        "reports/report_dto_formatter.module.cpp"
    )
else()
    set(TIME_TRACKER_INFRA_REPORTS_DTO_SOURCES
        "reports/report_dto_export_writer.cpp"
        "reports/report_dto_formatter.cpp"
    )
endif()

if(TT_CPP20_MODULES_EFFECTIVE)
    set(TIME_TRACKER_INFRA_REPORTS_QUERYING_SOURCES
        "reports/lazy_sqlite_report_query_service.module.cpp"
        "reports/report_service.module.cpp"
        "reports/services/daily_report_service.module.cpp"
        "reports/services/monthly_report_service.module.cpp"
        "reports/services/weekly_report_service.module.cpp"
        "reports/services/yearly_report_service.module.cpp"
    )
else()
    set(TIME_TRACKER_INFRA_REPORTS_QUERYING_SOURCES
        "reports/lazy_sqlite_report_query_service.cpp"
        "reports/report_service.cpp"
        "reports/services/daily_report_service.cpp"
        "reports/services/monthly_report_service.cpp"
        "reports/services/weekly_report_service.cpp"
        "reports/services/yearly_report_service.cpp"
    )
endif()

if(TT_CPP20_MODULES_EFFECTIVE)
    set(TIME_TRACKER_INFRA_REPORTS_DATA_QUERYING_SOURCES
        "reports/lazy_sqlite_report_data_query_service.module.cpp"
        "reports/sqlite_report_data_query_service.module.cpp"
    )
else()
    set(TIME_TRACKER_INFRA_REPORTS_DATA_QUERYING_SOURCES
        "reports/lazy_sqlite_report_data_query_service.cpp"
        "reports/sqlite_report_data_query_service.cpp"
    )
endif()

set(TIME_TRACKER_INFRA_REPORTS_SOURCES
    ${TIME_TRACKER_INFRA_REPORTS_EXPORT_SOURCES}
    ${TIME_TRACKER_INFRA_REPORTS_DTO_SOURCES}
    ${TIME_TRACKER_INFRA_REPORTS_QUERYING_SOURCES}
    ${TIME_TRACKER_INFRA_REPORTS_DATA_QUERYING_SOURCES}
    "reports/facade/android_static_report_formatter_registrar.cpp"
    "reports/facade/android_static_report_formatter_registrar_support.cpp"
    "reports/facade/report_formatter_registry_adapter.cpp"
    "reports/daily/formatters/markdown/day_md_formatter_core.cpp"
    "reports/monthly/formatters/markdown/month_md_formatter_core.cpp"
    "reports/range/formatters/markdown/range_md_formatter_core.cpp"
)

if(TT_REPORT_ENABLE_LATEX)
    list(APPEND TIME_TRACKER_INFRA_REPORTS_SOURCES
        "reports/daily/formatters/latex/day_tex_formatter_core.cpp"
        "reports/daily/formatters/latex/day_tex_utils.cpp"
        "reports/daily/formatters/statistics/latex_strategy.cpp"
        "reports/monthly/formatters/latex/month_tex_formatter_core.cpp"
        "reports/monthly/formatters/latex/month_tex_utils.cpp"
        "reports/range/formatters/latex/range_tex_formatter_core.cpp"
        "reports/range/formatters/latex/range_tex_utils.cpp"
    )
endif()

if(TT_REPORT_ENABLE_TYPST)
    list(APPEND TIME_TRACKER_INFRA_REPORTS_SOURCES
        "reports/daily/formatters/typst/day_typ_formatter_core.cpp"
        "reports/daily/formatters/typst/day_typ_utils.cpp"
        "reports/daily/formatters/statistics/typst_strategy.cpp"
        "reports/monthly/formatters/typst/month_typ_formatter_core.cpp"
        "reports/range/formatters/typst/range_typ_formatter_core.cpp"
    )
endif()
