build:
  maxIssues: 0

complexity:
  CyclomaticComplexMethod:
    threshold: 20
    excludes:
      - '**/ui/screen/**'
      - '**/ui/**'
      - '**/test/**'
      - '**/androidTest/**'
      - '**/commonTest/**'
      - '**/jvmTest/**'
      - '**/androidUnitTest/**'
      - '**/androidInstrumentedTest/**'
      - '**/jsTest/**'
      - '**/iosTest/**'
  ComplexCondition:
    threshold: 6
    excludes: ['**/ui/**']
  LongMethod:
    threshold: 80
    excludes:
      - '**/ui/screen/**'
      - '**/ui/**'
      - '**/test/**'
      - '**/androidTest/**'
      - '**/commonTest/**'
      - '**/jvmTest/**'
      - '**/androidUnitTest/**'
      - '**/androidInstrumentedTest/**'
      - '**/jsTest/**'
      - '**/iosTest/**'
  LongParameterList:
    excludes:
      - '**/ui/screen/**'
      - '**/ui/**'
      - '**/contract/**'
      - '**/runtime/**/controller/**'
      - '**/runtime/**/services/**'
      - '**/test/**'
      - '**/androidTest/**'
      - '**/commonTest/**'
      - '**/jvmTest/**'
      - '**/androidUnitTest/**'
      - '**/androidInstrumentedTest/**'
      - '**/jsTest/**'
      - '**/iosTest/**'
  NestedBlockDepth:
    excludes:
      - '**/test/**'
      - '**/androidTest/**'
      - '**/commonTest/**'
      - '**/jvmTest/**'
      - '**/androidUnitTest/**'
      - '**/androidInstrumentedTest/**'
      - '**/jsTest/**'
      - '**/iosTest/**'
  TooManyFunctions:
    thresholdInClasses: 14
    excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/androidUnitTest/**', '**/androidInstrumentedTest/**', '**/jsTest/**', '**/iosTest/**', '**/ui/**']

naming:
  FunctionNaming:
    functionPattern: '([a-z][a-zA-Z0-9]*|[A-Z][a-zA-Z0-9]*)'
  InvalidPackageDeclaration:
    active: false
  MatchingDeclarationName:
    excludes:
      - '**/contract/**'
      - '**/ui/**'
  TopLevelPropertyNaming:
    constantPattern: '[A-Za-z][_A-Za-z0-9]*'

exceptions:
  TooGenericExceptionCaught:
    excludes: ['**/runtime/**']

style:
  LoopWithTooManyJumpStatements:
    maxJumpCount: 2
    excludes: ['**/ui/**']
  MagicNumber:
    excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/androidUnitTest/**', '**/androidInstrumentedTest/**', '**/jsTest/**', '**/iosTest/**', '**/*.kts', '**/ui/**']
    ignorePropertyDeclaration: true
  MaxLineLength:
    maxLineLength: 160
    excludes:
      - '**/ui/**'
      - '**/test/**'
      - '**/androidTest/**'
      - '**/commonTest/**'
      - '**/jvmTest/**'
      - '**/androidUnitTest/**'
      - '**/androidInstrumentedTest/**'
      - '**/jsTest/**'
      - '**/iosTest/**'
  ReturnCount:
    max: 5
    excludes:
      - '**/ui/**'
      - '**/test/**'
      - '**/androidTest/**'
      - '**/commonTest/**'
      - '**/jvmTest/**'
      - '**/androidUnitTest/**'
      - '**/androidInstrumentedTest/**'
      - '**/jsTest/**'
      - '**/iosTest/**'
  UnusedParameter:
    excludes: ['**/ui/**']
  UnusedPrivateProperty:
    excludes: ['**/ui/**']
