[apps.tracer_core]
path = "apps/tracer_core_shell"
cmake_source_path = "apps/tracer_core_shell"
cmake_flags = [
    "-G", "Ninja",
    "-D", "CMAKE_BUILD_TYPE=Release",
    "-D", "DISABLE_OPTIMIZATION=ON",
    "-D", "WARNING_LEVEL=0",
    "-D", "TIDY_WARNINGS_AS_ERRORS=OFF"
]

[apps.tracer_core_shell]
path = "apps/tracer_core_shell"
cmake_source_path = "apps/tracer_core_shell"
cmake_flags = [
    "-G", "Ninja",
    "-D", "CMAKE_BUILD_TYPE=Release",
    "-D", "DISABLE_OPTIMIZATION=ON",
    "-D", "WARNING_LEVEL=0",
    "-D", "TIDY_WARNINGS_AS_ERRORS=OFF"
]

[apps.tracer_windows_rust_cli]
path = "apps/tracer_cli/windows/rust_cli"
backend = "cargo"
config_sync_target = "windows"

[apps.tracer_android]
path = "apps/tracer_android"
backend = "gradle"
fixed_build_dir = "build"
gradle_wrapper = "gradlew.bat"
config_sync_target = "android"
gradle_tasks = [
    ":app:assembleDebug",
]

[apps.log_generator]
path = "apps/tools/log_generator"
cmake_flags = [
    "-G", "Ninja",
    "-D", "CMAKE_BUILD_TYPE=Release",
    "-D", "DISABLE_OPTIMIZATION=ON",
    "-D", "WARNING_LEVEL=0",
    "-D", "TIDY_WARNINGS_AS_ERRORS=OFF"
]
