// infra/tests/modules_smoke/insights.hpp
#ifndef TRACER_CORE_TESTS_INFRASTRUCTURE_MODULES_SMOKE_INSIGHTS_HPP_
#define TRACER_CORE_TESTS_INFRASTRUCTURE_MODULES_SMOKE_INSIGHTS_HPP_

auto RunInfrastructureModuleInsightsSmoke() -> int;

#endif  // TRACER_CORE_TESTS_INFRASTRUCTURE_MODULES_SMOKE_INSIGHTS_HPP_
