// infra/tests/modules_smoke/reporting.hpp
#ifndef TRACER_CORE_TESTS_INFRASTRUCTURE_MODULES_SMOKE_REPORTING_HPP_
#define TRACER_CORE_TESTS_INFRASTRUCTURE_MODULES_SMOKE_REPORTING_HPP_

auto RunInfrastructureModuleReportsSmoke() -> int;

#endif  // TRACER_CORE_TESTS_INFRASTRUCTURE_MODULES_SMOKE_REPORTING_HPP_
