parent = "recreation"
color = "#000000"

[canonical.online-platforms]
"zhihu" = ["zhihu", "知乎"]
"douyin" = ["douyin", "抖音"]
"bilibili" = ["bilibili", "哔哩哔哩"]
"weibo" = ["weibo"]

[canonical.game]
"minecraft" = ["minecraft"]
"overwatch" = ["守望先锋", "overwatch"]
"clash-royale" = ["皇室战争", "cr", "Clash Royale"]
