parent = "exercise"

[aliases]
"围棋" = "go"
"普拉提" = "pilates"
"瑜伽" = "yoga"

[aliases.cardio]
group_aliases = ["有氧训练"]
"游泳" = "swimming"
"骑行" = "cycling"

[aliases.cardio.running]
group_aliases = ["跑步"]
"操场跑" = "track-running"
"跑步机" = "treadmill"
"跑步机爬坡" = "treadmill-incline"

[aliases.strength-training]
group_aliases = ["无氧训练"]

[aliases.strength-training.pull]
group_aliases = ["拉"]
"引体" = "pull-up"
"杠铃划船" = "barbell-row"

[aliases.strength-training.push]
group_aliases = ["推"]
"卧推" = "bench-press"
"站姿杠铃肩推" = "overhead-press"
"臂屈伸" = "dips"

[aliases.strength-training.squat]
group_aliases = ["蹲"]
"深蹲" = "squat"
"硬拉" = "deadlift"
"颈前深蹲" = "front-squat"
