from pathlib import Path

from .guidance import Guidance, read_guidance_content


def build_profile_markdown(
    *,
    profile_display_name: str,
    scan: dict,
    summary: dict,
    groups: list[dict],
    priority_groups: list[dict],
    module_summaries: list[dict],
    module_reading_candidates: list[dict],
    missing_paths: list[Path],
    workspace_root: Path,
) -> str:
    lines = [
        "# LOC Scanner Context Report", "",
        f"- Profile: `{profile_display_name}`",
        f"- Mode: `{scan.get('mode', '')}`",
        f"- Matched files: `{summary.get('matched_files', 0)}`", "",
        "This report is generated by the LOC scanner. The architecture guidance",
        "documents remain the source of truth; this file is a local snapshot for",
        "agent and developer review.", "",
        "## Module Reading Candidates (Suggested)", "",
    ]
    if not module_reading_candidates:
        lines.extend(["No module reading candidates are available.", ""])
    else:
        lines.extend([
            "| Suggested Rank | Module | Reading Score | Priority | Reasons |",
            "| ---: | --- | ---: | ---: | --- |",
        ])
        for candidate in module_reading_candidates:
            lines.append(
                f"| {candidate['reading_rank']} | `{candidate['display_name']}` | "
                f"{candidate['reading_score']:.2f} | P{candidate['priority']} | "
                f"{'；'.join(candidate['reasons'])} |"
            )
        lines.append("")

    lines.extend(["## Module Baseline Summary", ""])
    if not module_summaries:
        lines.extend(["No module baseline is available.", ""])
    else:
        lines.extend([
            "| Module | Files | LOC | Production | Path Tests | Inline Tests | Hotspots | Directories | Labels |",
            "| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | --- |",
        ])
        for module in module_summaries:
            production = module["source_sets"]["production"]
            tests = module["source_sets"]["tests"]
            inline_tests = module.get("test_evidence", {}).get("inline_tests", {})
            lines.append(
                f"| `{module['display_name']}` | {module['files']} | "
                f"{module['lines']} | {production['files']} files / "
                f"{production['lines']} lines | {tests['files']} files / "
                f"{tests['lines']} lines | {inline_tests.get('files', 0)} files / "
                f"{inline_tests.get('lines', 0)} estimated lines | {module['matched_files']} | "
                f"{module['source_directories']} | "
                f"{', '.join(module.get('labels', [])) or 'none'} |"
            )
        lines.extend(["", "### Top Files by Module", ""])
        for module in module_summaries:
            lines.extend([f"#### {module['display_name']}", ""])
            for item in module["top_files"]:
                matched = "hotspot" if item["matched"] else "below threshold"
                lines.append(
                    f"- `{item['path']}` — {item['lines']} lines, "
                    f"`{item['category']}`, `{item['language']}`, {matched}"
                )
            lines.append("")
            if module.get("label_reasons"):
                lines.append("Labels:")
                for label in module["labels"]:
                    lines.append(f"- `{label}`: {module['label_reasons'].get(label, '')}")
                lines.append("")

    assessed_modules = [
        module for module in module_summaries
        if module.get("assessment", {}).get("signals")
    ]
    if assessed_modules:
        lines.extend(["## Component Assessments", ""])
        lines.extend([
            "These are evidence-based review prompts, not automatic refactoring decisions.",
            "",
        ])
        for module in assessed_modules:
            assessment = module["assessment"]
            lines.extend([f"### {module['display_name']}", ""])
            for signal in assessment["signals"]:
                lines.append(f"- `{signal['code']}`: {signal['reason']}")
            lines.append("")

    lines.extend(["## Hotspot Findings", ""])
    if not priority_groups:
        lines.extend(["No files matched the selected threshold.", ""])
    else:
        for priority_group in priority_groups:
            lines.extend([f"### P{priority_group['priority']}", ""])
            for finding in priority_group["findings"]:
                lines.extend([
                    f"#### `{finding['path']}` ({finding['lines']} lines)", "",
                    f"- Component: `{finding['display_name']}`",
                    f"- Category: `{finding['category']}`",
                    f"- Language: `{finding['language']}`",
                    f"- Context hint: {finding.get('guidance', {}).get('summary', '')}",
                    f"- Context source: `{finding.get('guidance', {}).get('path') or 'none'}`", "",
                ])

    lines.extend(["## Component Context", ""])
    seen_paths: set[str] = set()
    for group in groups:
        guidance_data = group.get("guidance", {})
        guidance_path = guidance_data.get("path")
        lines.extend([
            f"### {group['display_name']}", "",
            f"- Category: `{group['category']}`",
            f"- Context hint: {guidance_data.get('summary', '')}",
            f"- Context source: `{guidance_path or 'none'}`", "",
        ])
        if guidance_path and guidance_path not in seen_paths:
            seen_paths.add(guidance_path)
            content = read_guidance_content(
                workspace_root,
                Guidance(
                    summary=guidance_data.get("summary", ""),
                    path=guidance_path,
                    validation=tuple(guidance_data.get("validation", [])),
                ),
            )
            if content:
                lines.extend(["#### Full Guidance Snapshot", "", content.rstrip(), ""])

    if missing_paths:
        lines.extend(["## Missing Paths", ""])
        lines.extend(f"- `{path}`" for path in missing_paths)
        lines.append("")
    return "\n".join(lines)
