if(NOT DEFINED OUTPUT_PATH OR OUTPUT_PATH STREQUAL "")
    message(FATAL_ERROR "GenerateBuildMetadata.cmake: OUTPUT_PATH is required.")
endif()

if(NOT DEFINED HEADER_GUARD OR HEADER_GUARD STREQUAL "")
    message(FATAL_ERROR "GenerateBuildMetadata.cmake: HEADER_GUARD is required.")
endif()

if(NOT DEFINED DATE_MACRO OR DATE_MACRO STREQUAL "")
    message(FATAL_ERROR "GenerateBuildMetadata.cmake: DATE_MACRO is required.")
endif()

if(NOT DEFINED TIMESTAMP_MACRO OR TIMESTAMP_MACRO STREQUAL "")
    message(FATAL_ERROR "GenerateBuildMetadata.cmake: TIMESTAMP_MACRO is required.")
endif()

string(TIMESTAMP BUILD_DATE_UTC "%Y-%m-%d" UTC)
string(TIMESTAMP BUILD_TIMESTAMP_UTC "%Y-%m-%dT%H:%M:%SZ" UTC)

get_filename_component(OUTPUT_DIR "${OUTPUT_PATH}" DIRECTORY)
file(MAKE_DIRECTORY "${OUTPUT_DIR}")

string(CONCAT METADATA_HEADER_CONTENT
    "// Auto-generated by CMake at build time. Do not edit.\n"
    "#ifndef ${HEADER_GUARD}\n"
    "#define ${HEADER_GUARD}\n"
    "\n"
    "#define ${DATE_MACRO} \"${BUILD_DATE_UTC}\"\n"
    "#define ${TIMESTAMP_MACRO} \"${BUILD_TIMESTAMP_UTC}\"\n"
    "\n"
    "#endif  // ${HEADER_GUARD}\n"
)

file(WRITE "${OUTPUT_PATH}" "${METADATA_HEADER_CONTENT}")
