set(TIME_TRACKER_APPLICATION_BOOTSTRAP_SOURCES
    "bootstrap/startup_validator.cpp"
    "workflow_handler.cpp"
    "reporting/report_handler.cpp"
    "reporting/tree/project_tree_viewer.cpp"
    "importer/import_service.cpp"
    "parser/memory_parser.cpp"
    "service/log_processor.cpp"
    "service/converter_service.cpp"
    "parser/text_parser.cpp"
)
